### ISSUE TITLE
Stop Search once find any result

### ISSUE THREAD

**Issue by wangxiangtao** [robert-bor/aho-corasick#22]
Hi robert, 

Is it possible to add a feature or another method to stop searching the tire once find any keyword. 

because i have requirement which only want to check exist or not.  

it will be more efficient if have this function.   think it is easy to add it to make the library more stronger:)

Thanks

**Comment by robert-bor** [comment]
How about you are able to set the configuration like this:

```java
        trie.stopOnHit();
```

The library will stop once it emits at least once.

Note that multiple emits may have been generated.
