### ISSUE TITLE
Maintaining additional node information

### ISSUE THREAD

**Issue by rajanjana** [robert-bor/aho-corasick#30]
Hi,

First of all thanks for providing an implementation of the algorithm. 

Wanted to check -
Is there a way to maintain additional information along with each keyword/node within the trie data structure ? Basically whenever there is a match, I would like to retrieve corresponding match information.

For example,
Assume we have 10 documents each having distinct words. I can create the trie by adding the words as keywords to the trie builder. However, whenever there is a match, I would like to know from which document the word came from. So, need to maintain some extra information like document id in each of the node of the trie along with the words.

Let me know if you need more information.

Thanks,
Rajan Jana

**Comment by robert-bor** [comment]
Hi Rajan. That is not possible with this library. I would recommend forking the library and patching it to be able to do what you require.

**Comment by rajanjana** [comment]
Hi Robert,

Thanks for the reply. I analyzed the changes I need to make to support this feature and seems like it is much more involved work to support additional information per node. Let me take a look at it and see how it can be done best. I will provide more information once I have any concrete update. Once again thank you for the implementation.

Thanks,
Rajan Jana

**Comment by robert-bor** [comment]
You're welcome! Good luck with the envisioned change.
