### ISSUE TITLE
Missing null check in Emit.toString()

### ISSUE THREAD

**Issue by broadhu2** [robert-bor/aho-corasick#32]
Using version 0.3.0. I tried this code on a test file in Eclipse:

```
for(String line; (line = br.readLine()) != null; ) {
    Emit firstMatch = trie.firstMatch(line);
    System.out.println(firstMatch.toString());
}
```

and received a `java.lang.NullPointerException`. I changed it to the following and got expected behavior (no more `NullPointerException`):

```
for(String line; (line = br.readLine()) != null; ) {
    Emit firstMatch = trie.firstMatch(line);
    System.out.println(firstMatch);
}
```

I think you are missing a `null` dereference check somewhere in your overrided `toString()` implementations. Minor issue, but also easy to fix.

**Comment by DaveJarvis** [comment]
The `Emit` `toString` method:

```
    public String toString() {
        return super.toString() + "=" + this.keyword;
    }
```

The `super.toString` is null-safe:

```
    public String toString() {
        return this.start + ":" + this.end;
    }
```

The start and end values are primitives, so they cannot be null.

The `Trie.firstMatch` method, line 187 can return null, and probably does if there are no matches. This could throw an exception, instead. Either way, the toString method looks fine.

Re-open if you disagree.

**Comment by broadhu2** [comment]
That is fine with me. Thank you for the explanation.
