### ISSUE TITLE
caseInsensitive() must be called before addKeyword()

### ISSUE THREAD

**Issue by broadhu2** [robert-bor/aho-corasick#33]
Hi,

I noticed that if you call `caseInsensitive()` configuration method after `addKeyword(...)` method then `trie.firstMatch()` and anything else that returns an `Emit` type will always return `null` for those keywords added before calling the case insensitive configuration method. This can be avoided by calling the `caseInsensitive()` configuration method before calling `addKeyword(...)` method as in your examples, but I think you should make it clear in the documentation somewhere that the order matters for `caseInsensitive()`, or change the code to check for different possible orderings during the `build()` process. The other configuration methods like `onlyWholeWords()` work fine regardless of when they are invoked.

For example, the following returns `null` for `emit`:

```
Trie trie = Trie.builder()
    .addKeyword(...)
    .caseInsensitive()
    .build();

Emit emit = trie.firstMatch(...);
```

But this works fine:

```
Trie trie = Trie.builder()
    .caseInsensitive()
    .addKeyword(...)
    .build();

Emit emit = trie.firstMatch(...);
```

**Comment by DaveJarvis** [comment]
Added comments to a new branch. Will be included in the next release.

**Comment by broadhu2** [comment]
Thanks!
