### ISSUE TITLE
Behavior at scale

### ISSUE THREAD

**Issue by cyberjoac** [robert-bor/aho-corasick#35]
Hello,

I tried using the algorithm when scanning for 6M of values, but I got a Java out of heap space error.
`java.lang.OutOfMemoryError: Java heap space`

What would be the changes needed to support Aho-Corasick at scale ?
Could augmenting the heap space of the JVM be sufficient or is a bigger refactoring needed to support scale ? 
Any alternatives (either AC or another algorithm) that could scale well, maybe being distributed ? 

Thanks for any pointers to a possible solution.

**Comment by almondtools** [comment]
Maybe you want to consider [StringAndChars ](https://github.com/almondtools/stringsandchars). It is tested against large documents in my project [StringBench](https://github.com/almondtools/stringbench). 

Yet I tried to compare StringsAndChars it with AhoCorasick, but the latter fails with a performance problem (https://github.com/robert-bor/aho-corasick/issues/36), maybe both issues are dependent.

**Comment by DaveJarvis** [comment]
Perhaps using [BigList](http://www.magicwerk.org/page-collections-download.html) will resolve the issue?

**Comment by matanster** [comment]
@cyberjoac any follow up on that? you haven't specified how much memory you had allocated to the JVM

**Comment by cyberjoac** [comment]
@matanster, at the time we added some memory to the JVM and it fixed the issue.
