### ISSUE TITLE
Performance Issue with Overlaps

### ISSUE THREAD

**Issue by almondtools** [robert-bor/aho-corasick#36]
I encountered a performance problem, documented in a Unit-Test https://github.com/almondtools/stringbench/blob/master/src/test/java/com/almondtools/stringbench/incubation/ACAhoCorasickIncubationTest.java.

I tracked down the reason: The `removeOverlaps`-Method removes overlaps in an inefficient way. The experiments show, that following section is the critical one:

```
for (Intervalable removeInterval : removeIntervals) {
   intervals.remove(removeInterval);
 }
```

Doing this on an ArrayList consumens O(n^2) and an ArrayList containing millons of elements will have long to work.

**Comment by DaveJarvis** [comment]
See issue #35, which suggests a different list implementation for DefaultEmitHandler.
