### ISSUE TITLE
Add list of keywords to Trie

### ISSUE THREAD

**Issue by DaveJarvis** [robert-bor/aho-corasick#42]
The Trie class should take an array and/or of keywords. Rather than:

```
        .addKeyword("hers")
        .addKeyword("his")
        .addKeyword("she")
        .addKeyword("he")
```

It should be possible to add them all at once:

```
        .addKeywords(new String[]{"hers", "his", "she", "he"})
```

**Comment by isapir** [comment]
Looks like it's the `Trie.TrieBuilder` class and not `Trie` itself, but a big **+1** from me.

**Comment by DaveJarvis** [comment]
Fix is on branch. Takes a list, an argument list, or a CharacterSequence.
