### ISSUE TITLE
Allow to specify Payload with Keyword

### ISSUE THREAD

**Issue by isapir** [robert-bor/aho-corasick#49]
It'd be great if each keyword could have an associated object that is used as a payload.  That way the Trie can store associated data with each keyword, and Emits can retrieve that data in addition to just the keyword and its index position.

**Comment by DaveJarvis** [comment]
Do you have a use case for this? It's a good idea, but might be out of scope. As alternative would be to let Trie be subclassed so you could write:

```
Trie trie = MyTrie.builder().build();
```

Within MyTrie, you could do something like:

```
protected Emit createEmit() {
  return new MyEmit();
}
```

This would allow data customizations, post-processing, and other Liskov-respectful behaviours.

**Comment by isapir** [comment]
I believe that there are many use cases for this.

Currently, I am planning to use it with several different sets of keywords, each set has different "definitions", and each keyword might have its own definitions.  The definitions describe the type of the keyword, and other information, e.g. how the keyword should be "processed" if matched.

As it is now, I need to maintain a separate Map that will map each keyword to the definition, but if I could set a payload object as proposed, then the definitions of that keyword can be stored with it, and then the Emit can return the definitions without the need to do a lookup in a separate Map.

I will look into the suggestions that you made, thanks.

**Comment by DaveJarvis** [comment]
See also:

- http://stackoverflow.com/questions/17164375/subclassing-a-java-builder-class
- http://www.artima.com/weblogs/viewpost.jsp?thread=133275
- http://egalluzzo.blogspot.ca/2010/06/using-inheritance-with-fluent.html
- http://stackoverflow.com/a/10941465/59087

**Comment by isapir** [comment]
Yes, there are different ways to handle this, but I still think that there is a very valid reason to implement this proposal.  

I would argue that in most cases more information is needed for each keyword than the just the string (keyword) itself.  It's great to find fast that the input string contains keywords in the Trie, but what do you do with that information next?  If you're just doing a find/replace then yes, you don't need any more information.

But let's say for example that you are doing Natural Language Processing.  You can then store with each keyword the Part of Speech, i.e. whether it's a noun, a verb, an adjective, etc.

Another example is if you want to detect hacking attempts for a Web Application Firewall.  You can have different sets of keywords, e.g. a set for SQL Injection, a set for Cross Site Scripting, etc., and have that information handy with the Emits, so that if the keyword `iframe` was detected, you already know that this is an XSS attack without doing an additional lookup elsewhere.

**Comment by DaveJarvis** [comment]
The [Open-Closed Principle](https://en.wikipedia.org/wiki/Open/closed_principle) suggests that we should keep Trie as generic as possible (i.e., simple searches, no payload) and provide a `PayloadTrie` subclass (or however named).

I agree: there are lots of situations where a payload is useful. For those situations where a payload is not required (e.g., simple search and replace), then the payload would otherwise be additional data hanging around in memory for no reason. Seems a bit wasteful.

**Comment by isapir** [comment]
Fair enough.  

How do you feel about adding a `PayloadTrie` (or however named) class to the project?

**Comment by DaveJarvis** [comment]
I think it's a good idea, @isapir, and it'll be quite useful for others.

Would you like to implement it and issue a PR? It'll probably require changes to the Trie class so that it can use builder subclasses.

**Comment by isapir** [comment]
I will look into it.  Thanks.

**Comment by Immueggpain** [comment]
@DaveJarvis wait! you know `Trie` only has a private constructor right?

**Comment by DaveJarvis** [comment]
> @DaveJarvis wait! you know `Trie` only has a private constructor right?

I did at the time. Right now:

```
    public static TrieBuilder builder() {
        return new TrieBuilder();
}
```

The code tightly couples the Trie, TrieBuilder, and TrieConfig, preventing further customization independently from the library itself. Seems to be a violation of the Dependency Inversion Principle. That will take a fair amount of refactoring to resolve.

**Comment by danbeck** [comment]
I added a pull request that adds the possibility to add "payloads" for each keyword. See https://github.com/robert-bor/aho-corasick/pull/68

Could someone review the patch?
