### ISSUE TITLE
Use regexp in keywords

### ISSUE THREAD

**Issue by hathija** [robert-bor/aho-corasick#50]
Hello,

First of all, i would like to thanks this project which really help me in some of my projects.

Can you advice me if it can be possible to use keyword in keywords ?
If yes, how can you do that ?

Thanks for the reply,

**Comment by robert-bor** [comment]
An interesting thought experiment I went through myself as well. If you look at the underlying algorithm, you will come to understand why regular expressions are not support. Basically, the algorithm create a tree-structure of letters, where the branches of the tree form the search words. Doing this enables you to very efficiently search a text for multiple words. However, the price you pay is the loss of flexibility that a regular expression offers.

So, regrettably, regular expressions are not supported in this library.
