### ISSUE TITLE
Pom file for 0.3.1 release cannot be found on the maven central

### ISSUE THREAD

**Issue by plokhotnyuk** [robert-bor/aho-corasick#52]
It is listed, but cannot be downloaded from here:
http://repo1.maven.org/maven2/org/ahocorasick/ahocorasick/0.3.1/

**Comment by robert-bor** [comment]
Hi @plokhotnyuk . That's correct, just pushed it this morning. It should pop up somewhere within the next 20 hours or so.

**Comment by plokhotnyuk** [comment]
@robert-bor I see that other files (jars and hashsumes) are available, so I'm not sure that .pom file will be available w/o reporting to the maven central support

**Comment by robert-bor** [comment]
Maven Central publication takes some time to fully publish. Does it work for you now?

**Comment by plokhotnyuk** [comment]
No, it doesn't. Now whole release directory returns 404

**Comment by plokhotnyuk** [comment]
Now it works for me.
