### ISSUE TITLE
Allow to ack emits

### ISSUE THREAD

**Issue by Crystark** [robert-bor/aho-corasick#53]
Hi,

I was taking a look at how `storeEmit` works (https://github.com/robert-bor/aho-corasick/blob/master/src/main/java/org/ahocorasick/trie/Trie.java#L277) and thought it could be nice if the `emitted` boolean was based on a value returned by `emitHandler.emit`. This would allow us to do additional checks on values before acking an emit and thus taking advantage of `isStopOnHit`.

In my case, I have a post condition based on each keyword. I would like to stop as soon as I find a match that also satisfies the post condition. Currently, even if I override the emit handler, i have no way of forcing a stop.

**Comment by DaveJarvis** [comment]
```
public interface EmitHandler {
    void emit(Emit emit);
}
```

Could be:

```
public interface EmitHandler<R> {
    R emit(Emit emit);
}
```

Would that help?

**Comment by Crystark** [comment]
Thanks for your reply

The idea is that on [L282](https://github.com/robert-bor/aho-corasick/blob/master/src/main/java/org/ahocorasick/trie/Trie.java#L282) the code could be adapted like that:

```java
        if (emits != null && !emits.isEmpty()) {
            for (final String emit : emits) {
                emitted = emitHandler.emit(new Emit(position - emit.length() + 1, position, emit)) || emitted;
            }
        }
```
That allows for the emitHandler to say if yes or no an entry was acked by it. Note the `|| emitted` at the end of the line that garanties that once `emitted` is true it doesn't switch back to false.

So the interface would be:
```java
public interface EmitHandler {
    boolean emit(Emit emit);
}
```
let me know what you think.

**Comment by DaveJarvis** [comment]
```
emitted = emitHandler.emit(new Emit(position - emit.length() + 1, position, emit)) || emitted;
if(emitted && trieConfig.isStopOnHit()) break;
```

Can be:

```
emitted = emitHandler.emit(new Emit(position - emit.length() + 1, position, emit));
if(emitted && trieConfig.isStopOnHit()) {
  // Equivalent to "return true"
  break;
}
```

No need to track the old value of emitted.

**Comment by Crystark** [comment]
If you do that and `isStopOnHit` is false and say some entries in the loop were "emitted" but not the last one, then `storeEmits` will return `false`. 
It won't have an impact on the `parseText` method but it kinda breaks what the returned boolean means which originally is "did we successfully emit something ?". That's the only reason why I was making sure `emitted` stays true.

**Comment by DaveJarvis** [comment]
Yes, you are correct, the `|| emitted` is necessary.

**Comment by robert-bor** [comment]
Great idea, @Crystark . Approved.

**Comment by Crystark** [comment]
Great :) I'm looking forward to the new release!

**Comment by robert-bor** [comment]
If you want, feel free to draw up a pull request and make your mark on this library as a contributor :)

**Comment by Crystark** [comment]
I'll see if I can find some time but i probably won't be able to do it before next week.

**Comment by Crystark** [comment]
@robert-bor there you go. Better late than never ;)

**Comment by robert-bor** [comment]
Thanks @Crystark !
