### ISSUE TITLE
Use this algorithm for url matching (strings)

### ISSUE THREAD

**Issue by garimamannan** [robert-bor/aho-corasick#58]
Can this algo be modified to accomplish URL pattern matching to return exact (best) match instead of first match? 
modify State.java to have String instead of Character and compare strings based on "/" tokenizer in a way that doesn't impact performance?

**Comment by DaveJarvis** [comment]
> modify State.java to have String instead of Character and compare strings based on "/" tokenizer in a way that doesn't impact performance?

Have you tried making the change and profiling the difference?

**Comment by DaveJarvis** [comment]
Closing due to no answers from question.
