### ISSUE TITLE
Performance concern

### ISSUE THREAD

**Issue by greenlaw110** [robert-bor/aho-corasick#59]
I have a simple [microbenchmark](https://github.com/greenlaw110/java-str-benchmark/tree/string-match-algorithms) project to measure the string matching performance with different algorithms.

It looks to me Aho-Corasick performance doesn't look very cool in comparing with others:

| test scenario | String | KMP | KMP - precompiled | Aho-Corasick |
| :---         |  ---: | ---: | ---: | ---: |
| short text | `*78,763.767/ms` | `19,118.220/ms` | `29,489.667/ms` | `7824.821/ms` |
| long text | `*4,093.381/ms` | `329.124/ms` | `426.696/ms` | `197.690/ms` |

Is it because the design of my tests doesn't fit Aho-Corasick's typical usage scenario?

**Comment by robert-bor** [comment]
Took a quick look at the benchmark. From what I gather, the benchmark tests for looking for a single phrase in a text. If this is indeed the case, then you have tested correctly that this is not the strong suit of aho-corasick.

The algorithm is strongest if you look for multiple words in a text. The reason for this is that it converts the text you are searching in into a kind of index (the Trie). Then it runs through that index exactly once for all the words you are searching for.

The best way to benchmark the algorithm, would be to set up a single Trie of a large body of text (for example, Shakespeare) and then use a large set different words (for example, a dictionary) to look for matches. Basic String.indexOf would repeatedly search the same text, where AC uses the Trie and runs through it just once. The more words you are searching for, the faster it becomes in comparison.

Hope this helps :)

**Comment by DaveJarvis** [comment]
See also the benchmarks here: https://stackoverflow.com/a/40836618/59087

**Comment by greenlaw110** [comment]
Thanks @robert-bor and @DaveJarvis I will revamp the test case

**Comment by DaveJarvis** [comment]
Closing due to no further feedback.
