### ISSUE TITLE
Stop Trie#removePartialMatches() from being O(n^2)

### ISSUE THREAD

**Issue by LukeButtersFunnelback** [robert-bor/aho-corasick#61]
Hi
`org.ahocorasick.trie.Trie.removePartialMatches(CharSequence, List<Emit>)` is slow when the given list is large. The problem is because of the n^2 running time where a list of `Emit`s to delete is made and then each one is removed (not by index) from the list.

If you are happy to move to java 8 the change you need to make to speed this up is to change the method to be removePartialMatches:
```
collectedEmits.removeIf(e -> this.isPartialMatch(searchText, e));
```
This resulted in a speed up of `1941053ms` to `142ms` for some test that somehow used that method I think the doc was 8MB had lots of emits

**Comment by SageAgastya** [comment]
In fact its actually 1941053(ms) -> 142(ms)

**Comment by DaveJarvis** [comment]
Keep in mind that not all organizations (due to red tape) have moved to Java 8 (e.g., governments). Instead, I'd recommend adding a fast list implementation that is open source.

* http://www.magicwerk.org/res/collections/javadoc/org/magicwerk/brownies/collections/BigList.html
* http://www.magicwerk.org/page-collections-download.html

Another possibility is to use a linked list for the collected emits.

* https://docs.oracle.com/javase/7/docs/api/java/util/LinkedList.html

Lines 218 - 220 and 235 - 237 are duplicated and could use a little refactoring.

Come to mention it, **removePartialMatches** and **removePartialMatchesWhiteSpaceSeparated** are practically identical and the duplication can be eliminated.

Regarding the following snippet:

``` .java
        for (final Emit emit : collectedEmits) {
            if (isPartialMatch(searchText, emit)) {
                removeEmits.add(emit);
            }
        }

        for (final Emit removeEmit : removeEmits) {
            collectedEmits.remove(removeEmit);
        }
```

Looks like it could be [written](https://docs.oracle.com/javase/7/docs/api/java/util/Collection.html#removeAll(java.util.Collection)), which is still O(n^2), but in fewer lines:

``` .java
        for (final Emit emit : collectedEmits) {
            if (isPartialMatch(searchText, emit)) {
                removeEmits.add(emit);
            }
        }

        collectedEmits.removeAll(removeEmit);
````

Since looping twice problematic, yet another approach is to use an iterator:

``` .java
final Iterator<Emit> iterator = collectedEmits.iterator();

while(iterator.hasNext()) {
    final Emit emit = iterator.next();

    if ( isPartialMatch( searchText, emit ) ) {
        collectedEmits.remove( emit );
    }
}
```

I'd recommend refactoring the two methods to eliminate the duplication, then use an iterator to reduce the loop to O(n).

**Comment by LukeButtersFunnelback** [comment]
It is still extremely slow using the iterator, probably because of the shifting everything from the right to the left.

**Comment by LukeButtersFunnelback** [comment]
Doing something like:
```
package org.ahocorasick.trie;

import java.util.ArrayList;
import java.util.List;

public class ListHelper {

    public static interface RemovePredicate<T> {
        public boolean remove(T t);
    }
    
    public <T> void removeIf(List<T> list, RemovePredicate<T> predicate) {
        //TODO do something different with linked lists?
        int removeCount = 0;
        List<T> newList = new ArrayList<>();
        
        Object[] elementData = list.toArray();
        final int size = list.size();
        for (int i=0; i < size; i++) {
            T element = list.get(i); 
            if (!predicate.remove(element)) {
                newList.add(element);
            }
        }
        
        list.clear();
        list.addAll(newList);
    }
}
```
and then using it with:
```
    private void removePartialMatches(final CharSequence searchText, final List<Emit> collectedEmits) {
        RemovePredicate<Emit> remover = new RemovePredicate<Emit>() {

            @Override
            public boolean remove(Emit emit) {
                return isPartialMatch(searchText, emit);
            }
            
        };
        
        new ListHelper().removeIf(collectedEmits, remover);
    }
```
results in pretty good performance

**Comment by DaveJarvis** [comment]
Another set of ideas: https://stackoverflow.com/a/2048374/59087

A LinkedList looks like it'll perform well.

**Comment by LukeButtersFunnelback** [comment]
Trying it out it seems like a linked list performs poorly (using the iterator method).

**Comment by LukeButtersFunnelback** [comment]
So I think using the following makes sense as it is fast for array list and isn't super horrible for linked lists.
Would you like a MR?
```
package org.ahocorasick.trie;

import java.util.ArrayList;
import java.util.List;

public class ListHelper {

    public static interface RemovePredicate<T> {
        public boolean remove(T t);
    }
    
    public <T> void removeIf(List<T> list, RemovePredicate<T> predicate) {
        List<T> newList = new ArrayList<>();
        final int size = list.size();
        
        for(T element : list) { 
            if (!predicate.remove(element)) {
                newList.add(element);
            }
        }
        
        list.clear();
        list.addAll(newList);
    }
}
```

**Comment by DaveJarvis** [comment]
> Would you like a MR?

Yes, please, with `final` modifiers where possible.

Incidentally, is there a way to eliminate the creation of a `new ListHelper()` per `removePartialMatches` call?

Thanks for the help and effort.

**Comment by LukeButtersFunnelback** [comment]
Made the pull request https://github.com/robert-bor/aho-corasick/pull/62

I did make the new array list the size of the given list.

**Comment by LukeButtersFunnelback** [comment]
cool, thanks for accepting
