### ISSUE TITLE
New versions unavailable on Maven Central 

### ISSUE THREAD

**Issue by andreas-niemoeller-qhr** [robert-bor/aho-corasick#73]
I tried using the code but unfortunately version newer than 0.4.0 do not seem to be available through the Maven Central repository anymore.
Would it be possible to push the artifacts to Maven Central for 0.6.0 and future releases again?

**Comment by DaveJarvis** [comment]
There are some Javadoc issues that need to be fixed before pushing. If you'd care to correct them, that would be helpful. Otherwise, I'm not going to be able to get to this for at least another month.
