### ISSUE TITLE
Question about thread safety

### ISSUE THREAD

**Issue by urisimchoni** [robert-bor/aho-corasick#74]
Hi,

As much as I gather without going too deeply into the implementation, it looks safe to build the Trie once and then search it in parallel (call trie.parseText() on the same Trie instance from multiple threads).

This is because all the "state" of the search appears to be on local variables on the stack.

This is of course ignoring the issue of memory barriers that can be dealt with by making the Trie instance volatile.

Is this assesment correct?

Thanks,
Uri

**Comment by DaveJarvis** [comment]
Uri, if you have time to write a unit test that tests for thread-safety, that would be incredibly helpful.

**Comment by DaveJarvis** [comment]
> Is this assessment correct?

The test looks good, so I think the question has been answered.

If you encounter any issues with threading, please re-open this comment.
