### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by tomasherman** [robert-bor/aho-corasick#77]
Hello,

i would like to ask whether this library is considered production ready? or whether it's being used somewhere?

Thanks!

**Comment by DaveJarvis** [comment]
There are a few issues (NPEs) that have been addressed with the most recent changes. More unit tests to complete code coverage would be useful. I've used it in https://github.com/DaveJarvis/scrivenvar without any issues for a few years now, but Scrivenvar doesn't make use of the API exhaustively.
