### ISSUE TITLE
Building repeatedly.

### ISSUE THREAD

**Issue by shubhamrangadal** [robert-bor/aho-corasick#78]
Any issues are if I do this repeatedly.

fun checkList(list):
            Trie trie = Trie.builder().stopOnHit().ignoreCase().addKeywords(list).build();
            return trie.containsMatch(text);

**Comment by DaveJarvis** [comment]
> Any issues are if I do this repeatedly.

Would you care to write a unit test to ensure that this behaves as you expect?

If it doesn't behave as you expect, would you mind writing up a minimal working example that clearly demonstrates the issue?
