### ISSUE TITLE
Do you plan to upload latest version to Maven Central?

### ISSUE THREAD

**Issue by alexandersavin93** [robert-bor/aho-corasick#79]

**Comment by DaveJarvis** [comment]
@robert-bor, your thoughts on this?

**Comment by austinarbor** [comment]
Not as good as maven, but you can use jitpack to get the latest version https://jitpack.io/#robert-bor/aho-corasick/v0.6.1

**Comment by DaveJarvis** [comment]
In the process of getting permission from Sonatype to upload.
