### ISSUE TITLE
Missing releases on Maven Central

### ISSUE THREAD

**Issue by ctmay4** [robert-bor/aho-corasick#88]
The latest release of the library on Maven Central is version 0.4.0 from 2017.  There have been 4 releases since then.

https://search.maven.org/classic/#search%7Cgav%7C1%7Cg%3A%22org.ahocorasick%22%20AND%20a%3A%22ahocorasick%22

Are they being released somewhere else?  Thanks.

**Comment by DaveJarvis** [comment]
@ctmay4, no they haven't been released elsewhere. The original author has gone silent and I hadn't voluntarily put any of my time into figuring out how to deploy to Maven Central. I finally got around to making a release for 0.6.2 last night, but it doesn't look like it has populated the repos.

**Comment by ctmay4** [comment]
So are you not planning on getting this released to Maven Central?  Its much less usable without newer fixes being available.  If the original author is not around then you may not have the keys for deploying to Maven Central under this package.  If that is the case, the only way to deploy this will be to change the package to something can be deployed.

**Comment by DaveJarvis** [comment]
> So are you not planning on getting this released to Maven Central?

It should have been deployed last night, but I may have missed a step. Agreed it isn't very usable without deployment.

**Comment by ctmay4** [comment]
Ok, sounds good.  Could it be related to this recent commit where the repository was removed?

https://github.com/robert-bor/aho-corasick/commit/2d7487f75429da8a9c501416434a520c375c2d40#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8

**Comment by DaveJarvis** [comment]
> Ok, sounds good. Could it be related to this recent commit where the repository was removed?

No. I would greatly enjoy being able to deploy from the command line, but I wasn't able to make it work. Instead, I deployed through the Nexus UI, but it didn't seem to stick for whatever reason.

![repo](https://user-images.githubusercontent.com/2131950/98736309-7e1fb200-2359-11eb-9491-d8fb387ca377.png)

**Comment by ctmay4** [comment]
Sonotype can definitely be frustrating.  I have automated my releases but they sometimes randomly timeout.  Usually if I try 2 or 3 times it will eventually work.  If not you can open a ticket with them.  They have been responsive to me in the past.
