### ISSUE TITLE
Release new artifacts to repositories?

### ISSUE THREAD

**Issue by avif** [robert-bor/aho-corasick#92]
Latest available version on maven central is 0.4.0, the current version seems to be 0.6.2 - can you update the repositories?

**Comment by DaveJarvis** [comment]
If someone would like to help get this onto Maven Central, please reply.

**Comment by robert-bor** [comment]
Released the v0.6.3 that Dave put in place.

**Comment by avif** [comment]
Is there any chance of auto deploying artifacts so that this is not needed anymore?
