### ISSUE TITLE
Can you release the OpenHarmony OS JS version？

### ISSUE THREAD

**Issue by hzjust** [robert-bor/aho-corasick#97]
I am developing an OpenHarmony application that uses the JavaScript language. Can you support the OpenHarmony JavaScript version? I am willing to participate in the development and look forward to reply.

**Comment by DaveJarvis** [comment]
This is a Java-based implementation of the Aho-Corasick algorithm. Java and JavaScript are different languages. If you're looking for a JavaScript-based implementation, you'll have to do some searching around.
