### ISSUE TITLE
NPE when the input text its null.

### ISSUE THREAD

**Issue by arturobernalg** [robert-bor/aho-corasick#99]
After created successfully the Trie,  in some case the input `textDocument` which causes a Null Pointer Exceptions.

`  final Trie trie = Trie.builder().
                onlyWholeWords().
                ignoreCase().
                stopOnHit().
                addKeywords(words).
                build();
        return trie.firstMatch(textDocument) != null;`

**Comment by DaveJarvis** [comment]
Thanks for the PR. I've updated the code to address the under-specified API call and to add assertions that enforce non-`null` values. I've merged your unit test, thanks for the addition!

I'd prefer the code be `null`-hostile than accept `null` as a valid input.

**Comment by DaveJarvis** [comment]
FWIW, returning an `Optional` than a `null` `Emit` instance would be a modest improvement. Even better, though, would be to register a listener that receives the `Emit`ted values. That would eliminate the possibility of having to check for `null` return values altogether.
